services:
  - type: web
    name: backend
    env: node
    runtime:
      version: '23.3.0'
    build:
      command: corepack enable && corepack prepare pnpm@9.12.1 --activate && pnpm install
    start:
      command: corepack enable && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '5000'
    healthCheck:
      path: '/'
      interval: 10
      timeout: 5
      retries: 3
    packageManager: pnpm@9.12.1
